[project]
name = "seg-comp"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pynput>=1.8.1",
]

[project.scripts]
start = "main:__main__"

[dependency-groups]
dev = ["pyright>=1.1.398", "ruff>=0.11.4"]
